### ISSUE TITLE
Package shouldn't be noarch, because of selector

### ISSUE THREAD

**Issue by nehaljwani** [AnacondaRecipes/mypy-feedstock#2]
Unless support for `py<38` has been dropped, this package cannot be `noarch: python`.

https://github.com/AnacondaRecipes/mypy-feedstock/blob/a63946347d6b1a332b947c7f6a131ee01dd7e268/recipe/meta.yaml#L30

Please see the issue at https://github.com/python/mypy/issues/10714

**Comment by nehaljwani** [comment]
I suspect that this could be an edge case which got missed by the new `DOR updates` mechanism. cc @chenghlee

**Comment by lriesebos** [comment]
Any updates on this issue?

**Comment by nehaljwani** [comment]
cc @remkade

**Comment by skupr-anaconda** [comment]
The issue is obsolete now
